import card from '../assets/card.jpg'
export const projectsData = [
  {
    id: 1,
    title: "DripCartel E-commerce",
    description: "Movie streaming app with TMDB API",
    image: card,
    tech: ["React", "Context API", "Tailwind", "React", "Context API", "Tailwind","React"],
    github: "https://github.com/abhishek/netflix",
    live: "https://netflix-clone.vercel.app",
  },
  {
    id: 2,
    title: "Swiggy Clone",
    description: "Food ordering app with real-time data",
    image: card,
    tech: ["React", "Redux", "Bootstrap"],
    github: "https://github.com/abhishek/swiggy",
    live: "",
  },
  {
    id: 3,
    title: "DripCartel - Clothing E-commerce",
    description: "Movie streaming app with TMDB API",
    image: card,
    tech: ["React", "Context API", "Tailwind"],
    github: "https://github.com/abhishek/netflix",
    live: "https://netflix-clone.vercel.app",
  },
  {
    id: 4,
    title: "Swiggy Clone",
    description: "Food ordering app with real-time data",
    image: card,
    tech: ["React", "Redux", "Bootstrap"],
    github: "https://github.com/abhishek/swiggy",
    live: "",
  },
  {
    id: 5,
    title: "DripCartel - Clothing E-commerce",
    description: "Movie streaming app with TMDB API",
    image: card,
    tech: ["React", "Context API", "Tailwind"],
    github: "https://github.com/abhishek/netflix",
    live: "https://netflix-clone.vercel.app",
  },
  {
    id: 6,
    title: "Swiggy Clone",
    description: "Food ordering app with real-time data",
    image: card,
    tech: ["React", "Redux", "Bootstrap"],
    github: "https://github.com/abhishek/swiggy",
    live: "",
  },
];